# Generated by Django 5.0 on 2023-12-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birthday', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universities.university')),
            ],
        ),
    ]
