# Generated by Django 5.0 on 2023-12-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='university',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
